name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run unit tests
        run: CGO_ENABLED=1 go test -v ./...

  integration-tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - name: Run integration tests
        run: ./test.sh
